#!/bin/sh
#
# @name HEAR quad ethernet indoor
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Abdulla Ayyad <abdulla.ayyad96@gmail.com>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

. ${R}etc/init.d/airframes/common_leaf/ekf2_indoor
. ${R}etc/init.d/airframes/common_leaf/mag/disable

. ${R}etc/init.d/airframes/common_leaf/estimator

. ${R}etc/init.d/airframes/common_leaf/safety

. ${R}etc/init.d/airframes/common_leaf/mav_0_router
. ${R}etc/init.d/airframes/common_leaf/mav_2_offboard

. ${R}etc/init.d/airframes/common_leaf/multirotor

. ${R}etc/init.d/airframes/common_leaf/ethernet

##################################################

control_allocator stop


