#!/bin/sh
#
# @name HEAR quad ethernet indoor
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Abdulla Ayyad <abdulla.ayyad96@gmail.com>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

. ${R}etc/init.d/airframes/common_leaf/ekf2_indoor.leaf
. ${R}etc/init.d/airframes/common_leaf/mag/disable.leaf

. ${R}etc/init.d/airframes/common_leaf/estimator.leaf

. ${R}etc/init.d/airframes/common_leaf/safety.leaf

. ${R}etc/init.d/airframes/common_leaf/mav_0_router.leaf
. ${R}etc/init.d/airframes/common_leaf/mav_2_offboard.leaf

. ${R}etc/init.d/airframes/common_leaf/multirotor.leaf

. ${R}etc/init.d/airframes/common_leaf/eth.leaf

##################################################

control_allocator stop


